#!/usr/bin/perl

system "cp", "Configure", "Configure.old";
open(IN, "Configure.old") || die "Can't open Configure.old\n";
open(OUT, ">Configure") || die "Can't write Configure\n";

while (<IN>) {
    next if /^(bison|chmod|chgrp|chown|compress|cpio|emacs|flex|gcc|line)='['\$]/;
    next if /^(lkflags|ln|lp|lpr|ls|mailx|make|mpack|objdir|pmake)='['\$]/;
    next if /^(pr|sh|shar|sleep|submit|tar|tbl|touch|troff|zcat)='['\$]/;
    next if /^(ar|gzip|zip)='['\$]/;
    next if /^(Author|Date|Header|Locker|RCSfile|Revision|Source|State)='['\$]/;

    if (/^(mimeshow|mimestore)='\$/) {
	s/'/"/g;
    }
    print OUT $_;
}
