name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux-build:
    runs-on: ubuntu-latest

    env: 
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        submodules: true
    - uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: CMake version
      run: cmake --version

    - name: CMake workflow
      run: cmake --workflow --preset ci-linux

  # Disabled until <curses.h> can be safely included without conflict in terminal.h
  # macos-build:
    # runs-on: macos-latest

    # env: 
    #   VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    # steps:
    # - uses: actions/checkout@v4.1.1
    #   with:
    #     submodules: true
    # - uses: actions/github-script@v7
    #   with:
    #     script: |
    #       core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
    #       core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    # - name: CMake workflow
    #   run: cmake --workflow --preset ci-linux

  windows-build:
    runs-on: windows-latest
    
    env: 
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        submodules: true
    - uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Download bison
      shell: powershell
      env:
        BISON_ZIP_URL: http://user.xmission.com/~legalize/trn/bison-2.4.1.zip
        BISON_ZIP_PATH: ${{github.workspace}}/../bison-2.4.1.zip
        BISON_PATH: ${{github.workspace}}/../bison
      run: |
        Invoke-WebRequest -Uri ${{env.BISON_ZIP_URL}} -OutFile "${{env.BISON_ZIP_PATH}}"
        mkdir ${{env.BISON_PATH}}
        cd ${{env.BISON_PATH}}
        7z x -y ${{env.BISON_ZIP_PATH}}
        Add-Content $env:GITHUB_PATH "${{env.BISON_PATH}}/bin"

    - name: CMake version
      run: cmake --version

    - name: CMake workflow
      run: cmake --workflow --preset default
