name: CMake

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-2022 ]
        # Disabled until <curses.h> can be safely included without conflict in terminal.h
        # os: [ ubuntu-latest, windows-2022, macos-latest ]
        include:
          - os: ubuntu-latest
            cmake-preset: ci-linux
          - os: windows-2022
            cmake-preset: default

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: true

    - name: Setup vcpkg package cache
      id: vc
      uses: LegalizeAdulthood/vcpkg-github-cache@4305d9f202bf0131458407402f0cc7efc3412394 # v1.1.0
      with:
        token: ${{github.token}}
        bootstrap: "true"
        install-nuget: "true"
        debug: "false"
        trace: "false"

    - name: CMake version
      run: cmake --version

    - name: CMake workflow
      shell: pwsh
      run: |
        cmake --workflow --preset ${{matrix.cmake-preset}} 2>&1 |
          Tee-Object -FilePath build.log
        if ($LASTEXITCODE -ne 0) {
          exit $LASTEXITCODE
        }

    - name: Analyze vcpkg package cache
      if: always()
      uses: LegalizeAdulthood/vcpkg-github-cache/analyze@4305d9f202bf0131458407402f0cc7efc3412394 # v1.1.0
      with:
        token: ${{github.token}}
        build-log: build.log
        artifact-name: vcpkg-cache-diagnostics-${{github.job}}-${{matrix.os}}-${{matrix.cmake-preset}}
        fail-on: "never"
        debug: "false"
        trace: "false"
