name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        # Disabled until <curses.h> can be safely included without conflict in terminal.h
        # os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{matrix.os}}

    env: 
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        submodules: true
    - uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: CMake version
      run: cmake --version

    - name: CMake Linux workflow
      if: ${{matrix.os == 'ubuntu-latest'}}
      run: cmake --workflow --preset ci-linux

    - name: CMake workflow
      if: ${{matrix.os != 'ubuntu-latest'}}
      run: cmake --workflow --preset default
