name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        # Disabled until <curses.h> can be safely included without conflict in terminal.h
        # os: [ ubuntu-latest, windows-latest, macos-latest ]
        include:
          - os: ubuntu-latest
            cmake-preset: ci-linux
            nuget: mono `${{github.workspace}}/vcpkg/vcpkg fetch nuget | tail -n 1`
          - os: windows-latest
            cmake-preset: default
            nuget: nuget

    runs-on: ${{matrix.os}}
    env: 
      FEED_URL: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        submodules: true

    - name: Install Prerequisites Linux
      if: ${{matrix.os == 'ubuntu-latest'}}
      shell: bash
      run: |
        ${{github.workspace}}/vcpkg/bootstrap-vcpkg.sh
        sudo apt install mono-complete

    - name: Add NuGet sources Linux
      if: ${{matrix.os == 'ubuntu-latest'}}
      shell: bash
      env: 
        VCPKG_EXE: ${{github.workspace}}/vcpkg/vcpkg
      run: |
        ${{matrix.nuget}} \
          sources add \
          -Source "${{env.FEED_URL}}" \
          -StorePasswordInClearText \
          -Name GitHubPackages \
          -UserName "${{github.repository_owner}}" \
          -Password "${{secrets.GH_PACKAGES_TOKEN}}"
        ${{matrix.nuget}} \
          setapikey "${{secrets.GH_PACKAGES_TOKEN}}" \
          -Source "${{env.FEED_URL}}"

    - name: Add NuGet sources Windows
      if: ${{matrix.os != 'ubuntu-latest'}}
      shell: bash
      run: |
        ${{matrix.nuget}} \
          sources add \
          -Source "${{env.FEED_URL}}" \
          -StorePasswordInClearText \
          -Name GitHubPackages \
          -UserName "${{github.repository_owner}}" \
          -Password "${{secrets.GH_PACKAGES_TOKEN}}"
        ${{matrix.nuget}} \
          setapikey "${{secrets.GH_PACKAGES_TOKEN}}" \
          -Source "${{env.FEED_URL}}"

    - name: CMake version
      run: cmake --version

    - name: CMake workflow
      env: 
        VCPKG_BINARY_SOURCES: "clear;nuget,${{env.FEED_URL}},readwrite"
      run: cmake --workflow --preset ${{matrix.cmake-preset}}
